### ISSUE TITLE
Salt Blocks Render Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [RedGalaxySoftware/TheModernity#2]
Explain the bug:
- Salt blocks will render with water flowing down its sides when placed underwater

<s>- Top Inner Seams of glass panes will also still render when multiple are placed on top of each other</s> (RGSW: moved to #5)

#### To Reproduce
1. Take a Salt Block
2. Place underwater

#### Expected Behavior:
- It should render similarly to Minecraft glass if placed underwater. 

#### Resources:
![2019-12-10_14 31 34](https://user-images.githubusercontent.com/12000593/70566647-1580f180-1b5a-11ea-9265-ab2cdde1c6c2.png)

_(RGSW: other image is moved to #5)_

#### Environment
- Modernity: Indev-0.3.0
- Forge: 28.1.104
- Minecraft: 1.14.4

**Comment by FoxSamu** [comment]
I'll split this issue into two separate issues: one for the salt block and one for the glass panes...
