### ISSUE TITLE
Picking up Oil will give a Lava Bucket

### ISSUE THREAD

**Issue by WenXin20** [RedGalaxySoftware/TheModernity#3]
Explain the bug:
- If I use an Iron or Aluminium Bucket on oil, I will instead receive an Iron Lava Bucket
- Aluminium Buckets cannot pick up water or lava.

#### To Reproduce:
1. Place Oil
2. Right-Click it with an aluminum or iron bucket.

#### Environment
- `Modernity: [Indev-0.3.0]`
- `Forge: [28.1.104]`
- `Minecraft: [1.14.4]`

**Comment by FoxSamu** [comment]
Aluminium buckets can't pick up water/lava intentionally (make a feature request if you really want this). But I'll look at the oil...

**Comment by WenXin20** [comment]
Alright, thanks

**Comment by WenXin20** [comment]
The same also happens with the modernized water and heatrock.

**Comment by FoxSamu** [comment]
Yes, I know... This bug is not really a bug but rather temporary behaviour: I still need to think about the behaviour of vanilla buckets on Modernity fluids. It should be either not possible or you would pick up the right fluid instead of a vanilla fluid...

**Comment by FoxSamu** [comment]
Picking up modernity fluids is no longer possible with vanilla bucket: that's intentional behaviour for now.
