### ISSUE TITLE
Saplings disappear when bonemealed

### ISSUE THREAD

**Issue by WenXin20** [RedGalaxySoftware/TheModernity#4]
Explain the bug:
- Both Inver and Blackwood saplings disappear when bonemealed.

#### To Reproduce:
1. Place a sapling
2. Right-Click it with bonemeal

#### Environment
- `Modernity: [Indev-0.3.0]`
- `Forge: [28.1.104]`
- `Minecraft: [1.14.4]`

**Comment by FoxSamu** [comment]
This is weird because I have fixed this multiple times... But I'll look at it...
