### ISSUE TITLE
Dark glass pane blocks don't cull vertical edges

### ISSUE THREAD

**Issue by FoxSamu** [RedGalaxySoftware/TheModernity#5]
Separated from #2 as that issue contained two issues...

![2019-12-10_14 36 12](https://user-images.githubusercontent.com/12000593/70566960-a1931900-1b5a-11ea-9d9d-223db5899275.png)

#### To Reproduce
Place some dark glass panes on top of each other: the top edge will not cull...

#### Environment
- Modernity: Indev-0.3.0
- Forge: 28.1.104
- Minecraft: 1.14.4

**Comment by FoxSamu** [comment]
@WenXin20 This issue seems to be caused by the mod that provides connected textures... Is that optifine? Please provide some more information...

**Comment by WenXin20** [comment]
Yes, I'm using Optifine, but I'm the one that was making the connected textures for modded blocks, when I found this issue with the dark glass panel.
It can probably be replicated without Optifine, but the connected textures are what made the bug obvious.

**Comment by FoxSamu** [comment]
Vanilla has the culling issue too but optifine fixes that... But there is a separate texure for glass pane sides you probably need to update too...

**Comment by WenXin20** [comment]
Sorry, forgot to reply. I don't think that the glass pane side texture needs to be changed by the texture pack. I haven't had to touch the side texture for any other glass panes from other mods at all.

After looking at the resources for Forbidden Arcanus as a reference to see how it defined it's Runic Glass Pane, as seen [here](https://github.com/stal111/Forbidden-Arcanus/blob/1.14/src/main/resources/assets/forbidden_arcanus/models/block/runic_glass_pane_noside.json), it looks like both `murky_glass_pane_noside.json` and `murky_glass_pane_noside_alt.json` should not have a defined edge texture. At least, that's my best guess after looking at how this mod and the other defined the glass pane models.

**Comment by FoxSamu** [comment]
Yes, you're right... But this is because the `noside` models don't use the edge texture... These are parts of the full model where no connection exists: they are the sides of the center pole only...

Anyways, the pane class I use does not derive from vanilla's pane class:
```java
public class PaneBlock extends WaterloggedBlock
```
I could check if this is the reason... More block classes do this and have therefore compatibility issues...

**Comment by FoxSamu** [comment]
The new update should have fixed it as the modernity pane class now inherits vanilla pane class. I can't be completely sure as I didn't get Optifine working in my IDE so I might be wrong.
